export const initialState = {
  userState: {},
  weatherState: {
    cityWeather: {
      cityName: "sai gon city",
      avrTemperature: 37,
      highTemperature: 65,
      lowTemperature: 34,
      typeIcon: "sunny",
      content:
        "Minimum temperature near 58 degrees. Maximum temperature near 88 degrees. Isolated showers will be possible afternoon, averaging < 0.10 inch. Lowest relative humidity near 29 percent. Expect 14 hours of sunshine, which is 93 percent of possible sunshine. Average winds will be Southwest at 3 MPH during the morning and Northwest at 4 MPH during the afternoon. \n\n",
      data: [
        {
          _id: "60d5dd96febb313cf42ce6f8",
          rainFall: 15,
          wingSpeed: 54,
          highTemperature: 77,
          lowTemperature: 34,
          typeIcon: "sunny",
          dateTime: "2021-06-25T13:43:50.917Z",
        },
        {
          _id: "60d5dd96febb313cf42ce6f9",
          rainFall: 15,
          wingSpeed: 54,
          highTemperature: 77,
          lowTemperature: 34,
          typeIcon: "rain",
        },
        {
          _id: "60d5dd96febb313cf42ce6fa",
          rainFall: 15,
          wingSpeed: 54,
          highTemperature: 77,
          lowTemperature: 34,
          typeIcon: "rain",
        },
        {
          _id: "60d5dd96febb313cf42ce6fb",
          rainFall: 15,
          wingSpeed: 54,
          highTemperature: 77,
          lowTemperature: 34,
          typeIcon: "thunder",
        },
        {
          _id: "60d5dd96febb313cf42ce6fc",
          rainFall: 15,
          wingSpeed: 54,
          highTemperature: 77,
          lowTemperature: 34,
          typeIcon: "dry",
        },
        {
          _id: "60d5dd96febb313cf42ce6fd",
          rainFall: 15,
          wingSpeed: 54,
          highTemperature: 77,
          lowTemperature: 34,
          typeIcon: "cloud",
        },
      ],
      dateTime: "2021-06-25T13:43:50.917Z",
    },
    weathers: [
      {
        _id: "60d4a64c79ac32175cfffc29",
        cityName: "nha trang",
        avrTemperature: 65,
        highTemperature: 23,
        lowTemperature: 65,
        typeIcon: "thunder",
        data: null,
        dateTime: "2021-06-24T15:35:40.662Z",
        __v: 0,
        content:
          "When writing a weather forecast, you need to state the general weather conditions such as sunny, cloudy, rainy, stormy, cloudy, low and high temperature and weather warnings like tornadoes, flooding, etc.\n\n",
      },
    ],
    isFetching: false,
    isUpload: false,
    isSelect: true,
  },
};
